### ISSUE TITLE
Pattern link encountered unexpected error

### ISSUE THREAD

**Issue by johnreytanquinco** [nuvoleweb/bootstrap_patterns#2]
After enabling all required modules and the theme bootstrap pattern theme "UI Patterns example theme 8.3.7", I was not able to access the /patterns overview page, getting this error message in Drupal logs.

```
Twig_Error_Loader: Template "./templates/metadata.html.twig" is not defined (Drupal\Core\Template\Loader\ThemeRegistryLoader: Unable to find template "./templates/metadata.html.twig" in the Drupal theme registry.). in Twig_Loader_Chain->getCacheKey() (line 36 of /opt/app-root/src/themes/custom/bootstrap_patterns/templates/overview/patterns-overview-page.html.twig).
```

Commenting out this line fix the issue.

**Comment by magick93** [comment]
Am also getting the same error.

**Comment by ademarco** [comment]
I've improved the build, check the README for new installation instructions, this should fix the error.

**Comment by johnreytanquinco** [comment]
Hi @ademarco , I have an updated composer file from the repo and run `composer install` but I dont actually need the `build` folder as we have our custom site. We just want to use UI Patterns as tools for bootstrap_pattern theme.

I even tried to git clone a fresh copy of the repo. I was able to apply the theme but getting unusual error with that message:
>Twig_Error_Loader: Template "./templates/metadata.html.twig" is not defined (Drupal\Core\Template\Loader\ThemeRegistryLoader: Unable to find template "./templates/metadata.html.twig" in the Drupal theme registry.). in Twig_Loader_Chain->getCacheKey() (line 36 of /opt/app-root/src/themes/custom/bootstrap_patterns/templates/overview/patterns-overview-page.html.twig).
