### ISSUE TITLE
Question about Carousel slideshow

### ISSUE THREAD

**Issue by antonov** [nuvoleweb/bootstrap_patterns#3]
Hi @ademarco , thanks for the module and samples, it looks really amazing.

I am trying to check how it works in case of collection items, in the carousel example which you provided, the slide item should be created as a separate pattern or there is some way to map the slide properties of title, image and description to some multivalued field?

**Comment by ademarco** [comment]
Yep that's yet another thing to fix and it's in the plans on the UI Patterns module, for the moment you need to implement your own preprocess hooks: http://ui-patterns.readthedocs.io/en/8.x-1.x/content/developer-documentation.html#working-with-pattern-suggestions
