### ISSUE TITLE
nowhere to login and Access Denied to patterns

### ISSUE THREAD

**Issue by laurencefass** [nuvoleweb/bootstrap_patterns#4]
i followed install instructions to the letter and i have a page displayed but nowhere to login, so Access Denied. screen dump follows...

UI Patterns
Install the UI Patterns module and click here to visit the Patterns Overview page.
Access denied
You are not authorized to access this page.
Demo site for the UI Patterns module. Brought to you by Nuvole and a team of wonderful contributors.

**Comment by ademarco** [comment]
Yes you need to login onto your site to access the patterns page, there is no link for that, just access `/user` path.
